# trx-cache for realtime data
redis:
  enabled: yes
  auth:
    enabled: false # TODO
  image:
    registry: docker.io
    pullPolicy: IfNotPresent
    repository: redis/redis-stack-server # TODO: not working yet
    tag: "7.0.6-RC5"
  master:
    persistence:
      enabled: false
    containerPorts:
      # port used by redis inside of the container
      redis: 13350
    service:
      ports:
        # port exposed by the redis k8s-service
        redis: 13350
    podSecurityContext:
      enabled: true 
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
    extraFlags:
      - "--loadmodule /opt/redis-stack/lib/redistimeseries.so ${REDISTIMESERIES_ARGS}"
      - "--loadmodule /opt/redis-stack/lib/rejson.so ${REDISJSON_ARGS}"
  replica:
    persistence:
      enabled: false
    containerPorts:
      # port used by redis inside of the container
      redis: 6379
    service:
      ports:
        # port exposed by the redis k8s-service
        redis: 6379
    podSecurityContext:
      enabled: true 
      runAsUser: 1000
      runAsGroup: 3000
      fsGroup: 2000
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
    extraFlags:
      - "--loadmodule /opt/redis-stack/lib/redistimeseries.so ${REDISTIMESERIES_ARGS}"
      - "--loadmodule /opt/redis-stack/lib/rejson.so ${REDISJSON_ARGS}"

mongodb:
  enabled: yes
  architecture: standalone
  # mongodb container port
  containerPorts:
    mongodb: 13250
  service:
    ports:
      # mongodb exposing service port
      mongodb: 13250
  # mongo pod security context
  podSecurityContext:
    enabled: true 
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  # mongo container security context
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
  auth:
    enabled: false # TODO
  persistence:
    enabled: false # TODO

processing:
  Envs:
    MONGO_URI: "mongodb://{{ .Release.Name }}-mongodb:13250"
ui:
  Envs:
    MONGO_URI: "mongodb://{{ .Release.Name }}-mongodb:13250"