apiVersion: v2
name: redis-stack
description: A Helm chart for Kubernetes

type: application

version: 17.7.2

dependencies:
  - name: common
    version: 2.2.3
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    condition: redis.enabled
    version: 17.7.2
    repository: https://charts.bitnami.com/bitnami
