apiVersion: v2
name: processing
description: Fraudaverse's Processing component which is responsible for realtime transaction scoring

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: v0.1.7
dependencies:
  - name: common
    version: 2.2.3
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    alias: redis-trx
    condition: redis-trx.enabled
    version: 17.7.2
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    alias: mongo-cfg-trx
    condition: mongo-cfg-trx.enabled
    version: 13.6.7
    repository: https://charts.bitnami.com/bitnami
