apiVersion: v1
kind: Service
metadata:
  name: {{ include "processing.fullname" . }}
  labels:
    {{- include "processing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "processing.selectorLabels" . | nindent 4 }}
